import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
  AiFillMediumCircle,
  AiFillGithub,
} from "react-icons/ai";

import { 
  FaReact,
  FaAngular,
  FaBootstrap,
  FaFigma,
} from "react-icons/fa";

import { 
  SiJavascript,
  SiTypescript,
  SiPython,
  SiPostgresql,
  SiSocketdotio,
  SiJsonwebtokens,
  SiCss3,
} from "react-icons/si";

import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Navbar from "./components/Navbar";
import swe from "../public/swe.JPG";
import poet from "../public/thepoet.jpeg";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.JPEG";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import Link from 'next/link';

export default function about() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>About Me</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
          <Link href='/'><h1 className="font-helvetica text-xl">SC</h1></Link>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <Navbar/>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="pb-10 text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Here's some stuff about me
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Shadman the Full-Stack Software Engineer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-3xl mx-auto md:text-xl">
            I've always seen myself as a creator. Ever since I was young, I could be found creating action figures out of sketches on pieces of paper and expressing myself through writing. Unfortunately, I was never able to use my creative side in school or college. I always saw my skills as a hobby and something that I could never use to pursue a career. In late 2021, my friend reignited his passion for development when he joined The Marcy Lab School, and as a fellow college burnout, I was intrigued. For the past year and a half, I have been following the 1% daily growth mantra and doing so has allowed me to finally use my creativity, combined with the skills I have gained in coding. My first project, For the Bees, aimed to raise awareness about the declining bee population through a visually appealing website designed with HTML and CSS. My second project, snkrHub, combined my love for sneakers and web development, creating a user-friendly portfolio for sneaker enthusiasts to curate and track their collections. My latest project, mentee. , showcases my full potential as a web developer and creative, by providing an innovative platform to connect underrepresented and nontraditional people in tech with mentors and community. I am proud of the unique and impactful projects I have created, demonstrating the power of combining creativity and technical skills.
            </p>
            <div className="rounded-lg p-5 mx-auto bg-gradient-to-b from-teal-500 w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={swe} layout="fill" objectFit="cover" />
            </div>

            <h3 className="pt-20 text-2xl py-2 dark:text-white md:text-3xl">
              Shadman the Creative
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-3xl mx-auto md:text-xl">
            As a multi-talented individual, I have had the privilege of delving into various forms of art throughout my life. From singing, dancing, drawing, and writing, I have explored the full spectrum of creative expression. My artistic nature extends beyond just these mediums and permeates into all aspects of my life. From the way I carefully curate my daily outfits, to the imaginative flair I bring to my software engineering projects, to the nightly reflections I document through sketches and journal entries.
            <br/>
            <br/>
            I am proud to call myself a creative at heart, and find solace in the written word whenever I experience heartbreak. My poetry, which can be found on my Instagram page @thelifeofshadman, offers a deeper insight into who I am as a person. While I may have dabbled in music and have a track on SoundCloud (not one of my finest moments), my true passion lies elsewhere.
            <br/>
            <br/>
            Software Engineering may be a profession I love and hold close to my heart, but I believe in having multiple passions and pursuing them all with equal fervor. One of my dreams is to start my own cafe-bar hybrid, where people can come to refuel and unwind. A bright and inviting space, filled with the aroma of espresso, natural greenery, and a hint of whiskey. By day, it would be a place for collaboration and productivity, while by night, it would be a cozy refuge to relax and do what your heart desires.
            </p>
            <div className="rounded-lg p-5 mx-auto bg-gradient-to-b from-teal-500 w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={poet} layout="fill" objectFit="cover" />
            </div>
          </div> 
        </section>
      </main>
    </div>
  );
}